title: Nicotine+
logo: /files/linux/nicotine-plus.svg
description: A graphical client for the SoulSeek peer-to-peer system

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

exclude:
  - files/linux/README
  - files/windows/README
  - img/README
  - plugins/README

theme: jekyll-theme-minimal
